### PR TITLE
Migrate to HPy 0.9.0

### PR DESCRIPTION
**Pull request by fangerer**

### CODE REVIEW

**Comment by mattip** [comment]
Thanks @fangerer 

I guess it would be nice to run the benchmarks...

**Comment by fangerer** [comment]
> Thanks @fangerer
> 
> I guess it would be nice to run the benchmarks...

They run (one iteration) in the CI. E.g.:

https://github.com/hpyproject/piconumpy/actions/runs/4872948103/jobs/8691840928#step:8:1

**Comment by mattip** [comment]
Ahh, nice. Does it make sense that the universal API is so fast? I wonder how GraalPython and PyPy stack up. I guess the benchmark CI could use the actions/setup-python@v4 to get a pypy3.9 and use the universal build to test it out, but that is something for another PR.
```
Julia                      :     1 * norm = 0.00282 s
PicoNumpy (CPython C-API)  :  10.4 * norm
PicoNumpy (HPy CPy ABI)    :  11.6 * norm
PicoNumpy (HPy Universal)  :  11.7 * norm
Transonic-Pythran          : 0.608 * norm
Numpy                      :  31.7 * norm
PicoNumpy (purepy)         :  39.2 * norm
PicoNumpy (purepy_array)   :    46 * norm
PicoNumpy (Cython)         :  35.8 * norm
```

**Comment by fangerer** [comment]
> Does it make sense that the universal API is so fast?

I think that's reasonable. `PicoNumpy (HPy Universal)` is  12.5% slower than `PicoNumpy (CPython C-API) `, right?

**Pull request merged**
