### PR TITLE
Bench hpy master (try again because of the strange diff for _piconumpy_hpy.c)

### PR DESCRIPTION
**Pull request by paugier**

### CODE REVIEW

**Comment by paugier** [comment]
I don't understand why there is this strange diff and why we don't see the mention "workflow awaiting approval":

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

It might be because this PR does not come from a fork but actually I propose a PR to a fork (hpyproject/piconumpy is a fork of paugier/piconumpy).

**Comment by paugier** [comment]
This is a mystery for me. The only positive thing is that Github Actions work in my repository : https://github.com/paugier/piconumpy/actions

**Comment by paugier** [comment]
Also the benchmark results are quite similar to what I obtain at home.

Of course, I can't yet run the CI with PyPy because it needs hpy > 0.0.2.

**Comment by mattip** [comment]
Once PyPy gets a hpy HEAD version merged to py3.7, you can add it to CI via [the pypy-3.7-nightly selector](https://github.com/actions/setup-python#specifying-a-pypy-version).

**Comment by paugier** [comment]
Yes, that's really nice to be able to use PyPy nightly so easily with Github Actions! I guess one would have to wait a bit for hpy 0.0.3 to be implemented in PyPy.

**Comment by antocuni** [comment]
> I don't understand why there is this strange diff

This is a mistery for me as well. If I checkout the PR (using `gh pr checkout 4`) and manually do a `git diff hpy`, the diff looks "normal" (i.e. `_piconumpy_hpy.c` is mostly the same).

Interestingly, `gh pr diff` shows the very same diff as here, so I am tempted to say that it's a github bug, but hopefully once it's merged it will do "the right thing".

I'll just merge it, thank you for doing it!

**Comment by antocuni** [comment]
@paugier I see that github actions are not run yet and I'm not sure how to enable them.
I sent you an invite to become a collaborator/admin of `hpyproject`, hopefully this should give you have all the required permissions

**Pull request merged**
